services:
  auth.api:
    image: ${DOCKER_REGISTRY-}authapi
    build:
      context: .
      dockerfile: Services/Auth/Auth.API/Dockerfile

  gw:
    image: ${DOCKER_REGISTRY-}gw
    build:
      context: .
      dockerfile: Services/GWAPI/GW/Dockerfile


  translation.api:
    image: ${DOCKER_REGISTRY-}translationapi
    build:
      context: .
      dockerfile: Services/Translation/Translation.API/Dockerfile

